apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: ghcr.io/morey-tech-bot/demo-app:71b7276d71db9ab36f017eade162ae17669b15c1
        name: demo-app
        ports:
        - containerPort: 8080
